package org.techniu.isbackend.exception;

public enum EntityType {
    EconomicStaffYear,
    EconomicStaffMonth,
    EconomicStaffExtra,
    Staff,
    StaffContract,
    StaffContractHistory,
    StaffDocuments,
    StaffEconomicContractInformation,
    StaffEconomicContractInformationHistory,
    City,
    CommercialOperationStatus,
    ServiceType,
    Client,
    ContractStatus,
    Iva,
    FinancialCompany,
    SectorCompany,
    Currency,
    CommercialOperation,
    AbsenceType,
    ContractType,
    LegalCategoryType,
    Contact,
    FunctionalStructureLevel,
    FunctionalStructureAssignationHistory,
    AdministrativeStructureLevel,
    AdministrativeStructureAssignationHistory,
    ContractModel,
    FinancialContract,
    Bill,
    ContactByOperation,
    CivilityTitle,
    EconomicStaff,
    Assignment
}
